<x-backend.layouts.partials.head/>
<body style="background-image: url('{{ asset('assets/bg-3.webp') }}');">
<div class="authentication">
    <div class="container">
        <div class="col-md-12 content-center">
            <div class="row">
                <div class="col-lg-6 col-md-12">
                    <div class="company_detail">
                        <h4 class="logo"><img src="{{asset('ui/main/assets/images/logo.svg')}}" alt=""> EMS</h4>
                        <h3 class="text-primary">EXAM <strong>MANAGEMENT </strong>SYSTEM</h3>
                        <p>It saves time as it allows number of students to give the exam at a time and displays the results as the test gets over, so no need to wait for the result. It is automaticaly generated by the server.</p>                        
                        <div class="footer">
                            <ul  class="social_link list-unstyled">
                                <li><a href="https://thememakker.com" title="ThemeMakker"><i class="zmdi zmdi-globe"></i></a></li>
                                <li><a href="https://themeforest.net/user/thememakker" title="Themeforest"><i class="zmdi zmdi-shield-check"></i></a></li>
                                <li><a href="https://www.linkedin.com/company/thememakker/" title="LinkedIn"><i class="zmdi zmdi-linkedin"></i></a></li>
                                <li><a href="https://www.facebook.com/thememakkerteam" title="Facebook"><i class="zmdi zmdi-facebook"></i></a></li>
                                <li><a href="http://twitter.com/thememakker" title="Twitter"><i class="zmdi zmdi-twitter"></i></a></li>
                                <li><a href="http://plus.google.com/+thememakker" title="Google plus"><i class="zmdi zmdi-google-plus"></i></a></li>
                                <li><a href="https://www.behance.net/thememakker" title="Behance"><i class="zmdi zmdi-behance"></i></a></li>
                            </ul>
                            <hr>
                            <ul>
                                <li><a href="http://thememakker.com/contact/" target="_blank">Contact Us</a></li>
                                <li><a href="http://thememakker.com/about/" target="_blank">About Us</a></li>
                                <li><a href="http://thememakker.com/services/" target="_blank">Services</a></li>
                                <li><a href="javascript:void(0);">FAQ</a></li>
                            </ul>
                        </div>
                    </div>                    
                </div>
                <div class="col-lg-5 col-md-12 offset-lg-1">
                    <div class="card-plain">
                        <div class="header">
                            <h5>Sign Up</h5>
                            <span>Register a new account</span>
                        </div>
                        <form method="POST" action="{{ route('register') }}">
                            @csrf                           
                            <div class="input-group">
                                <x-text-input id="name" class="form-control" type="text" name="name" :value="old('name')" required autofocus autocomplete="name" placeholder="Enter User Name" />
                                <span class="input-group-addon"><i class="zmdi zmdi-account-circle"></i></span>
                                <x-input-error :messages="$errors->get('name')" class="mt-2" />
                                
                            </div>
                            <div class="input-group">
                                <x-text-input id="email" class="form-control" type="email" name="email" :value="old('email')" placeholder="Enter Email" required autocomplete="username" />
                                <span class="input-group-addon"><i class="zmdi zmdi-email"></i></span>
                                <x-input-error :messages="$errors->get('email')" class="mt-2" />
                               
                            </div>
                            <div class="input-group">
                                <x-text-input id="password" class="form-control"
                            type="password"
                            name="password" placeholder="Password"
                            required autocomplete="new-password" />
                            <span class="input-group-addon"><i class="zmdi zmdi-lock"></i></span>

                            <x-input-error :messages="$errors->get('password')" class="mt-2" />
                                
                            </div>
                            <div class="input-group">
                                <x-text-input id="password_confirmation" class="form-control"
                            type="password"
                            name="password_confirmation" placeholder="Confirm Password"
                            required autocomplete="new-password" />
                            <span class="input-group-addon"><i class="zmdi zmdi-lock"></i></span>

                            <x-input-error :messages="$errors->get('password_confirmation')" class="mt-2" />
                                
                            </div>
                            <div class="checkbox">
                                <input id="terms" type="checkbox">
                                <label for="terms">I read and Agree to the <a href="javascript:void(0);">Terms of Usage</a></label>
                            </div>                            
                            <div class="footer">
                                <x-primary-button class="btn btn-primary btn-round btn-block">
                                    SIGN UP
                                </x-primary-button>
                            </div>
                        </form>
                        <a class="link" href="{{ route('login') }}">You already have an account?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<x-backend.layouts.partials.js/>